server:
  port: 8081

spring:
  application:
    name: uac-service

nacos:
  config:
    serverAddr: 127.0.0.1:8848
#    enableRemoteSyncConfig: true
#    bootstrap:
#      logEnable: true
  discovery:
    serverAddr: 127.0.0.1:8848
    autoRegister: true